#Web服务器：apache | nginx，通过交互式选择获取
zentao_webs: apache

zentao_vhost_dir: /etc/httpd/vhost
zentao_vhost_src: vhost.conf
zentao_service: httpd
zentao_owner: apache
zentao_name: "zentao"
zentao_title: "Zentao"
zentao_download_url: "https://github.com/easysoft/zentaopms.git"
zentao_version: "zentaopms_12.0.stable_20200103"   #版本号需定期维护