#Web服务器：apache | nginx，通过交互式选择获取
zentao_webs: apache

zentao_vhost_dir: /etc/httpd/vhost
zentao_vhost_src: vhost.conf
zentao_service: httpd
zentao_db_password: "123456"
zentao_owner: apache
zentao_name: "zentao"
zentao_title: "Zentao"
#下载链接需定期维护
zentao_download_url: 
  "zh": 
    "url": "http://dl.cnezsoft.com/zentao/12.0.1/ZenTaoPMS.12.0.1.zip"  
    
  "int": 
    "url": "http://dl.cnezsoft.com/zentao/12.0.1/ZenTaoALM.12.0.1.int.zip"
