name: Docs Build and Upload

on: 
  push:
    paths: docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: npm install vuepress
      run: |
       sudo npm install -g vuepress
        
    - name: vuepress build
      run: |
        cd docs
        sudo vuepress build .
      env:
        CI: true
    
    - name: Git Push
      run: |
        cd docs
        git clone https://github.com/Websoft9/websoft9.github.io.git
        cp -r html/* websoft9.github.io/docs/
        echo $(ls websoft9.github.io/docs/)
        cd websoft9.github.io
        echo "https://${{ secrets.ACCESS_TOKEN }}" > ~/.git-credentials
        git config --global credential.helper store
        git config --global user.email "xu_junkai@foxmail.com"
        git config --global user.name "Mozlk"
        git add .
        git commit -m "Add changes" 
        git push origin master
